### ISSUE TITLE
 What is the data structure of train_x and train_y?

### ISSUE THREAD

**Issue by dickkky** [jjdabr/forecastNet#1]
Could you provide specific data structure about train_x and train_y? For example, the setting of lag period and forecast period. Thx.

**Comment by sjyMystery** [comment]
The author is so awful.

**Comment by jjdabr** [comment]
Please see the function description of train() train.py (PyTorch), where it states
:param train_x: Input training data in the form [input_seq_length, batch_size, input_dim]
:param train_y: Target training data in the form [output_seq_length, batch_size, output_dim]
In the paper, the lag is input_seq_length = 2*tau and the number of forecast steps is output_seq_length = tau, where tau is the seasonal period of the data.
Note that "batch_size" is misleading; it should have been n_batches and has been corrected. Thank you for your question.
