### ISSUE TITLE
 t = 0 (t = t + 1, t + 2 ... t + 6 values),

### ISSUE THREAD

**Issue by 13121283123** [jjdabr/forecastNet#12]
Hello, I am very interested in your article and I have a question to ask you. for time t = 0, only the next one value (t = t + 1 value) was predicted? If I would predict the next 6 data sets at time t = 0 (t = t + 1, t + 2 ... t + 6 values), will your method work best?  I look forward to hearing from you very much.

**Comment by jjdabr** [comment]
Thank you for your interest. The model is specifically developed as a multi-step-ahead model, and it would thus be suitable to your application where you are looking for multiple forecasts (t = t + 1, t + 2 ... t + 6). I suggest having a look at our paper (see the link in the readme file), which will provide the details of how the model achieves this.
