### ISSUE TITLE
How can i train my dataset

### ISSUE THREAD

**Issue by YuxinFang21** [jjdabr/forecastNet#3]
There are multiple feature inputs ，and i want to  get a single forecast output. How should I modify the code to set the train_y?

**Comment by jjdabr** [comment]
Firstly, ensure that you are using the PyTorch code. The TensorFlow code does not support multiple input features; it only supports univariate input sequences.

When initialising the model, input_dim is the number of features in the input, output_dim is the number of features in the output, in_seq_length is the length of the input sequence, and out_seq_length is the length of the output sequence (number of forecast steps).

Format your data into the shape:
train_x: [in_seq_length, n_batches, input_dim]
train_y: [out_seq_length, n_batches, output_dim]

Train your model using the train function in train.py. Please refer to the documentation provided with each class and method for further details.

**Comment by YuxinFang21** [comment]
Thank you very much.I will try it!

**Comment by YuxinFang21** [comment]
> Firstly, ensure that you are using the PyTorch code. The TensorFlow code does not support multiple input features; it only supports univariate input sequences.
> 
> When initialising the model, input_dim is the number of features in the input, output_dim is the number of features in the output, in_seq_length is the length of the input sequence, and out_seq_length is the length of the output sequence (number of forecast steps).
> 
> Format your data into the shape:
> train_x: [in_seq_length, n_batches, input_dim]
> train_y: [out_seq_length, n_batches, output_dim]
> 
> Train your model using the train function in train.py. Please refer to the documentation provided with each class and method for further details.

Thanks for your reply.I have formated my data and trained it succesfully.However,it do not perform well .May the form of  inputing data is wrong.  
trainx:[in_seq_length, n_batches, input_dim]
Suppose I have 2000 data.Each time I input 100 to forecast 100 data .the number of features in the input is 8.
So, in_seq_length=100
n_batches=2000
input_dim=8
Is it right?
Thanks very much.
