### ISSUE TITLE
What is the meaning of n_batch?

### ISSUE THREAD

**Issue by YuxinFang21** [jjdabr/forecastNet#4]
Thanks for your last reply.I have formated my data and trained it succesfully.However,it do not perform well .May the form of inputing data is wrong.
trainx:[in_seq_length, n_batches, input_dim]
Suppose I have 2000 data.Each time I input 100 to forecast 100 data .the number of features in the input is 8.
So, in_seq_length=100
n_batches=2000
input_dim=8
Is it right?
Thanks very much.

**Comment by jjdabr** [comment]
If I understand you correctly, you have a data sequence with length 2000 and has 8 features. You want to be able to forecast 100 steps into the future. If so, you need to use a sliding window to extract the batches. 

For illustration, suppose you have a sequence with length 20 and has 2 features. The 20 sequence values are illustrated as follows:
`====================`
Suppose your input has length 4 and your output has length 3. You create a window for the input, denoted by [], and a window for the output, denoted by {} as follows:
`[====]{===}=============`
You extract the [====] and the {===} to form one input-output sample. You then shift the windows one sample over
`=[====]{===}============`
and extract the [====] and the {===} to form another input-output sample.
Continue shifting the windows one sample over and extracting the input-output samples
`==[====]{===}===========`
`...`
`============[====]{===}=`
until you reach the end:
`=============[====]{===}`
You should end up with 20-4-3+1=14 input-output samples. Recall that the input sample has length 4 and the output sample has length 3. The input can be represented as a tensor with shape (4, 14, 2) and the output can be represented as a tensor with shape (3, 14, 2); where 2 is the number of features. This forms the complete dataset. You pass this dataset to the training method. That is, you will have in_seq_length=4, n_batches=14, and input_dim=2. During training, this dataset will be split into batches according to the batch_size you specify. As I suggest in the documentation, it is probably better to change the train algorithm to use a PyTorch DataLoader; especially if you have a very large dataset.

I hope this helps.
