### ISSUE TITLE
 where is the dataset of ozone

### ISSUE THREAD

**Issue by 13121283123** [jjdabr/forecastNet#7]
boss！I'd like to quote your article. where is the dataset of ozone？ thank you

**Comment by jjdabr** [comment]
Thank you for your interest. The ozone dataset is the "Ozone, Arosa, 1932-1972" dataset found in Rob Hyndman's Time Series Data Library. I see the library has been moved here:
https://pkg.yangzhuoranyang.com/tsdl/
