### ISSUE TITLE
Train vs. evaluation output routing

### ISSUE THREAD

**Issue by felix-hilden** [jjdabr/forecastNet#8]
I'd like to ask about the output routing differences during training vs. evaluation. As described in the paper you feed in known values during training and values from the network during evaluation. This results in worse performance for the same set of data at evaluation.

Is there a reason for this, or is it even advantageous to do so? My intuition would be that optimising the output layer with further signals would lead to better results overall.

**Comment by jjdabr** [comment]
If I understand you correctly, you are referring to the teacher-forcing approach to training. This worked fine for the datasets in the paper. In general however, you can improve on this by randomly switching between providing the predictions and the ground truth during training. This is a common approach used in sequence-to-sequence models. For example, see https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html#training-the-model
