### ISSUE TITLE
yt=ft (ht) what is ft

### ISSUE THREAD

**Issue by 13121283123** [jjdabr/forecastNet#9]
I am very interested in your article. What do you mean by ft and gt when you prove time-variance, such as yt=ft (ht)?

**Comment by jjdabr** [comment]
Thank you for your interest. In the paper, ft describes the output layer and gt describes a hidden block in ForecastNet. The published paper may provide a better description for this. Here is a link

https://link.springer.com/chapter/10.1007/978-3-030-63836-8_48

(I have also updated the README file with this link)
